name: main

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test_ExoBLAS:
    steps:
      - name: test ExoBLAS on main push
        uses: ./.github/workflows/test_ExoBLAS.yml
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        with:
          exo-ref: main
          exo-blas-ref: main
      - name: test ExoBLAS on pull request
        uses: ./.github/workflows/test_ExoBLAS.yml
        if: github.event_name == 'pull_request'
        with:
          exo-ref: main
          exo-blas-ref: ${{ github.event.pull_request.merge_commit_sha }}
