name: main

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-test:
    needs: prepare-input
    uses: ./.github/workflows/build-test.yml
    with:
      exo-ref: main
      exo-blas-ref: ${{ github.ref }}
