name: main

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test_ExoBLAS_main_push:
    uses: ./.github/workflows/test_ExoBLAS.yml
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    with:
      exo-ref: main
      exo-blas-ref: main
  test_ExoBLAS_pull_request:
    uses: ./.github/workflows/test_ExoBLAS.yml
    if: github.event_name == 'pull_request'
    with:
      exo-ref: main
      exo-blas-ref: ${{ github.event.pull_request.merge_commit_sha }}
